name: ai-102-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.2.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - bottleneck=1.3.7
  - brotli-python=1.1.0
  - ca-certificates=2024.3.11
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - console_shortcut=0.1.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distro=1.8.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - flask=2.2.5
  - fqdn=1.5.1
  - freetype=2.12.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - idna=3.4
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - importlib_resources=6.3.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.12.0
  - isoduration=20.11.0
  - itsdangerous=2.0.1
  - jedi=0.19.1
  - jinja2=3.1.3
  - jpeg=9e
  - json5=0.9.22
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.4
  - jupyter_client=7.4.9
  - jupyter_core=4.12.0
  - jupyter_events=0.9.1
  - jupyter_server=2.13.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.4
  - lerc=3.0
  - libdeflate=1.17
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.2
  - nbformat=5.10.3
  - nest-asyncio=1.6.0
  - notebook=7.1.2
  - notebook-shim=0.2.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openai=1.9.0
  - openjpeg=2.4.0
  - openssl=3.0.13
  - overrides=7.7.0
  - packaging=24.0
  - pandas=2.2.1
  - pandas-stubs=2.1.4.231227
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  - pywin32=227
  - pywinpty=2.0.13
  - pyyaml=6.0.1
  - pyzmq=24.0.1
  - referencing=0.33.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - terminado=0.18.1
  - tinycss2=1.2.1
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.14.2
  - types-python-dateutil=2.9.0.20240316
  - types-pytz=2022.4.0.0
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - werkzeug=2.3.8
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - azure-ai-contentsafety==1.0.0
      - azure-ai-language-conversations==1.1.0
      - azure-ai-language-questionanswering==1.1.0
      - azure-ai-textanalytics==5.3.0
      - azure-ai-vision-imageanalysis==1.0.0b2
      - azure-cognitiveservices-speech==1.36.0
      - azure-cognitiveservices-vision-contentmoderator==1.0.0
      - azure-cognitiveservices-vision-customvision==3.1.0
      - azure-cognitiveservices-vision-face==0.6.0
      - azure-common==1.1.28
      - azure-core==1.30.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.50.0
      - isodate==0.6.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.3
      - msrest==0.7.1
      - oauthlib==3.2.2
      - pyparsing==3.1.2
      - python-dotenv==1.0.1
      - requests-oauthlib==1.4.0
      - wordcloud==1.9.3
